# AUTOGENERATED FROM 'app/queries/meeting/get_meeting_by_url_code.edgeql' WITH:
#     $ edgedb-py --dir app/queries/meeting --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import datetime
import uuid

import edgedb


@dataclasses.dataclass
class GetMeetingByUrlCodeResult:
    id: uuid.UUID
    url_code: str
    start_date: datetime.date | None
    end_date: datetime.date | None
    title: str
    location: str


async def get_meeting_by_url_code(
    executor: edgedb.AsyncIOExecutor,
    *,
    url_code: str,
) -> GetMeetingByUrlCodeResult | None:
    return await executor.query_single(
        """\
        with
            url_code := <str>$url_code,
        select Meeting { url_code, start_date, end_date, title, location }  # 컬럼 추가
        filter .url_code = url_code
        limit 1\
        """,
        url_code=url_code,
    )
