# AUTOGENERATED FROM 'app/queries/meeting/update_meeting_start_end.edgeql' WITH:
#     $ edgedb-py --dir app/queries/meeting --no-skip-pydantic-validation


from __future__ import annotations

import datetime
from typing import cast

import edgedb

from app.queries.meeting.models import FullMeeting


async def update_meeting_start_end(
    executor: edgedb.AsyncIOExecutor,
    *,
    url_code: str,
    start_date: datetime.date,
    end_date: datetime.date,
) -> FullMeeting | None:
    return cast(
        FullMeeting | None,
        await executor.query_single(
            """\
        with
            url_code := <str>$url_code,
            start_date := <cal::local_date>$start_date,
            end_date := <cal::local_date>$end_date,
        select (
            update Meeting
            filter .url_code = url_code
            set {start_date := start_date, end_date := end_date}
        ) {url_code, start_date, end_date, location, title}
        limit 1\
        """,
            url_code=url_code,
            start_date=start_date,
            end_date=end_date,
        ),
    )
