# AUTOGENERATED FROM 'app/queries/temp/update_meeting_location.edgeql' WITH:
#     $ edgedb-py --dir app/queries/temp --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import uuid
from typing import cast

import edgedb


@dataclasses.dataclass
class UpdateMeetingLocationResult:
    id: uuid.UUID


async def update_meeting_location(
    executor: edgedb.AsyncIOExecutor,
    *,
    url_code: str,
    location: str,
) -> UpdateMeetingLocationResult | None:
    return cast(
        UpdateMeetingLocationResult | None,
        await executor.query_single(
            """\
        with
            url_code := <str>$url_code,
          location := <str>$location,
        update Meeting
        filter .url_code = url_code
        set {location := location}\
        """,
            url_code=url_code,
            location=location,
        ),
    )
