# AUTOGENERATED FROM 'app/queries/temp/update_meeting_title.edgeql' WITH:
#     $ edgedb-py --dir app/queries/temp --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import uuid
from typing import cast

import edgedb


@dataclasses.dataclass
class UpdateMeetingTitleResult:
    id: uuid.UUID


async def update_meeting_title(
    executor: edgedb.AsyncIOExecutor,
    *,
    url_code: str,
    title: str,
) -> UpdateMeetingTitleResult | None:
    return cast(
        UpdateMeetingTitleResult | None,
        await executor.query_single(
            """\
        with
            url_code := <str>$url_code,
            title := <str>$title,
        update Meeting
        filter .url_code = url_code
        set {title := title}\
        """,
            url_code=url_code,
            title=title,
        ),
    )
