# AUTOGENERATED FROM 'app/queries/meeting/update_meeting_start_end.edgeql' WITH:
#     $ edgedb-py --dir app/queries/meeting --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import datetime
import uuid

import edgedb


@dataclasses.dataclass
class UpdateMeetingStartEndResult:
    id: uuid.UUID
    url_code: str
    start_date: datetime.date | None
    end_date: datetime.date | None
    location: str
    title: str


async def update_meeting_start_end(
    executor: edgedb.AsyncIOExecutor,
    *,
    url_code: str,
    start_date: datetime.date,
    end_date: datetime.date,
) -> UpdateMeetingStartEndResult | None:
    return await executor.query_single(
        """\
        with
            url_code := <str>$url_code,
            start_date := <cal::local_date>$start_date,
            end_date := <cal::local_date>$end_date,
        select (
            update Meeting
            filter .url_code = url_code
            set {start_date := start_date, end_date := end_date}
        ) {url_code, start_date, end_date, location, title}
        limit 1\
        """,
        url_code=url_code,
        start_date=start_date,
        end_date=end_date,
    )
